### ISSUE TITLE
Does it support image instead of canvas

### ISSUE THREAD

**Issue by hkcity1111** [ryanmc2033/angular-barcode#2] opened 2015-11-27 08:04 UTC
Hi 

Does it support image instead of canvas and How to configure the parameter to do this?
Thanks!

Regards
   Kenneth Lo

**Comment by justechn** [comment] 2015-11-27 16:09
Nope, but if you would like to add that feature I would be happy to accept
a pull request.

**Comment by eatskolnikov** [comment] 2015-12-31 17:08
I've added a pull request for this https://github.com/justechn/angular-barcode/pull/4

**Comment by justechn** [comment] 2016-02-08 01:12
@eatskolnikov After I merged it I realized there is a problem. It is caused by element.append, if someone changes their barcode it will add another element to the page instead of replacing the previous one. 

To see this happening open the example file. You will see that every few seconds a new barcode is added to the page. They should be just modifying the first one instead.

Can you fix this?

**Comment by eatskolnikov** [comment] 2016-02-08 01:21
@justechn sure, give me a few minutes

**Comment by eatskolnikov** [comment] 2016-02-08 04:07
@justechn done, check this PR https://github.com/justechn/angular-barcode/pull/8

**Closed as completed** 2016-02-12 04:20 UTC
